on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  release:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'release')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Release PR was merged
